import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:roms_downloader/utils/pack_naming.dart';

/// Proves the Dart port of `norm`, `displayTitle` and `canon` agrees with the
/// Python builder case by case, over the golden generated by
/// `tool/dump_naming_golden.py`.
///
/// If this breaks after a builder change, regenerate the golden and align the
/// Dart; do not relax the test.
void main() {
  late List<Map<String, dynamic>> cases;

  setUpAll(() {
    final raw = File('test/fixtures/naming_golden.json').readAsStringSync();
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    cases = (decoded['cases'] as List).cast<Map<String, dynamic>>();
    expect(cases.length, greaterThan(50), reason: 'golden empty or truncated');
  });

  test('norm agrees with the builder on every golden case', () {
    for (final c in cases) {
      expect(norm(c['input'] as String), c['norm'],
          reason: 'norm diverged on "${c['input']}"');
    }
  });

  test('displayTitle agrees with the builder on every golden case', () {
    for (final c in cases) {
      expect(displayTitle(c['input'] as String), c['displayTitle'],
          reason: 'displayTitle diverged on "${c['input']}"');
    }
  });

  test('canon agrees with the builder on every golden case', () {
    for (final c in cases) {
      expect(canon(c['input'] as String), c['canon'],
          reason: 'canon diverged on "${c['input']}"');
    }
  });
}
